swagger: '2.0'
info:
  title: HelpMeOut API
  description: API for recording and managing videos
  version: 1.0.0
basePath: /api
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /start-recording:
    post:
      summary: Start a new recording
      parameters:
        - name: user_id
          in: body
          required: true
          schema:
            type: string
      responses:
        201:
          description: Recording started successfully
          schema:
            type: object
            properties:
              message:
                type: string
              recording_id:
                type: string
              recording_url:
                type: string
  /recording/{id}:
    post:
      summary: Add video chunks
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: video
          in: formData
          type: file
          required: true
      responses:
        200:
          description: Recording stopped successfully
    get:
      summary: Get the video of a recording
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Video retrieved successfully
          content:
            video/mp4:
              schema:
                type: string
    put:
      summary: Update the title of a recording
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: title
          in: body
          required: true
          schema:
            type: string
      responses:
        200:
          description: Title updated successfully
    delete:
      summary: Delete a recording
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Recording deleted successfully
  /stop-recording/{id}:
    post:
      summary: Stop a recording
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: video
          in: formData
          type: file
          required: true
      responses:
        200:
          description: Recording stopped successfully
  /recording/transcript/{id}:
    get:
      summary: Get the transcript of a recording
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Transcript retrieved successfully
          content:
            text/plain:
              schema:
                type: string
  /recording/details/{id}:
    get:
      summary: Get details of a recording
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Recording details retrieved successfully
          schema:
            type: object
            properties:
              title:
                type: string
              recording_id:
                type: string
              recording_url:
                type: string
              creator_id:
                type: string
              time:
                type: string
              transcript_url:
                type: string
  /recording/user/{user_id}:
    get:
      summary: Get all recordings of a user
      parameters:
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: User recordings retrieved successfully
          schema:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                recording_id:
                  type: string
                recording_url:
                  type: string
                creator_id:
                  type: string
                time:
                  type: string
                transcript_url:
                  type: string
  /recording:
    get:
      summary: Get all recordings
      responses:
        200:
          description: All recordings retrieved successfully
          schema:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                recording_id:
                  type: string
                recording_url:
                  type: string
                creator_id:
                  type: string
                time:
                  type: string
                transcript_url:
                  type: string
